name: flutter_theme
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  kf_drawer:
  flutter_staggered_grid_view:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Roboto_Regular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Roboto_Bold
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
    - family: Roboto_Medium
      fonts:
        - asset: assets/fonts/Roboto-Medium.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splash.png
    - assets/images/cart1.png
    - assets/images/khung.png
    - assets/images/cart2.png
    - assets/images/adjust.png
    - assets/images/imagevai.png
    - assets/images/pizza.png
    - assets/images/piza.png
    - assets/images/burger.png
    - assets/images/vai.png
    - assets/images/ham.png
    - assets/images/avata.png
    - assets/images/tao.png
    - assets/images/nho.png
    - assets/images/dau.png
    - assets/images/vai.png
    - assets/images/tll.png
    - assets/images/dua.png
    - assets/images/mtao.png
    - assets/images/mham.png
    - assets/images/mpiza.png
    - assets/images/2.0x/star.png
    - assets/images/star.png
    - assets/images/crown.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:


  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
